#!/bin/bash

if [ -d "/etc/squid/" ]; then
	payload="/etc/squid/payload.txt"
elif [ -d "/etc/squid3/" ]; then
	payload="/etc/squid3/payload.txt"
fi
tput setaf 7
tput setab 4
tput bold
printf '%35s%s%-10s\n' "Agregar Host al Proxy Squid"
tput sgr0
if [ ! -f "$payload" ]; then
	tput setaf 7
	tput setab 4
	tput bold
	echo ""
	echo "Archivo $payload no encontrado"
	tput sgr0
	exit 1
else
	tput setaf 2
	tput bold
	echo ""
	echo "Dominios actuales en el archivo $payload:"
	tput sgr0
	tput setaf 3
	tput bold
	echo ""
	cat $payload
	echo ""
	tput sgr0
	read -p "Ingrese el dominio que desea agregar a la lista: " host
	if [[ -z $host ]]; then
		tput setaf 7
		tput setab 4
		tput bold
		echo ""
		echo "¡Ha ingresado un dominio vacío o no existente!"
		echo ""
		tput sgr0
		exit 1
	else
		if [[ $(grep -c "^$host" $payload) -eq 1 ]]; then
			tput setaf 7
			tput setab 4
			tput bold
			echo ""
			echo "El dominio $host ya existe en el archivo $payload"
			echo ""
			tput sgr0
			exit 1
		else
			if [[ $host != \.* ]]; then
				tput setaf 7
				tput setab 4
				tput bold
				echo ""
				echo "¡Debe agregar un dominio comenzando con un punto!"
				echo "Por ejemplo: .phreaker56.xyz"
				echo "No es necesario agregar subdominios para dominios que ya están en el archivo."
				echo "Es decir, no es necesario agregar recarga.claro.com.ar"
				echo "si el dominio .claro.com.ar ya está en el archivo."
				echo ""
				tput sgr0
				exit 1
			else
				echo "$host" >>$payload && grep -v "^$" $payload >/tmp/a && mv /tmp/a $payload
				tput setaf 7
				tput setab 1
				tput bold
				echo ""
				echo "Archivo $payload actualizado, el dominio se agregó con éxito:"
				tput sgr0
				tput setaf 3
				tput bold
				echo ""
				cat $payload
				echo ""
				tput sgr0
				if [ ! -f "/etc/init.d/squid3" ]; then
					service squid3 reload
				elif [ ! -f "/etc/init.d/squid" ]; then
					service squid reload
				fi
				tput setaf 7
				tput setab 1
				tput bold
				echo ""
				echo "¡El Proxy Squid se recargó con éxito!"
				echo ""
				tput sgr0
				exit 1
			fi
		fi
	fi
fi
