#!/bin/bash

clear

fun_bar() {

  comando[0]="$1"

  comando[1]="$2"

  (

    [[ -e $HOME/fim ]] && rm $HOME/fim

    ${comando[0]} >/dev/null 2>&1

    ${comando[1]} >/dev/null 2>&1

    touch $HOME/fim

  ) >/dev/null 2>&1 &

  tput civis

  echo -ne "   \033[1;33mESPERE \033[1;37m- \033[1;33m["

  while true; do

    for ((i = 0; i < 18; i++)); do

      echo -ne "\033[1;31m#"

      sleep 0.1s

    done

    [[ -e $HOME/fim ]] && rm $HOME/fim && break

    echo -e "\033[1;33m]"

    sleep 1s

    tput cuu1

    tput dl1

    echo -ne "   \033[1;33mESPERE \033[1;37m- \033[1;33m["

  done

  echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"

  tput cnorm

}

echo " "

fun_atts() {

  [[ -e /home/version ]] && rm /home/version

  [[ -e /tmp/att ]] && rm /tmp/att

  wget -c -P /home https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Install/version

  [[ -f "/home/version" ]] && mv /home/version /tmp/att

  [[ ! -e /bin/version ]] && rm -rf /bin/menu

} >/dev/null 2>&1

echo -e "                              \033[1;31mBy T3MMA\033[1;36m"

echo -e "   SSHPlus" | figlet

echo " "

echo -e "   \033[1;32mVERIFICANDO ACTUALIZACIÓN DISPONIBLE\033[0m\n"

fun_bar 'fun_atts'

[[ ! -f "/tmp/att" ]] && {

  echo -e "\n\033[1;31m ERROR AL CONECTAR CON EL SERVIDOR\n"

  echo -ne "\033[1;31m ENTER \033[1;33mpara volver al \033[1;32mMENU!\033[0m"
  read

  menu

}

echo " "

vrs1=$(sed -n '1 p' /bin/version | sed -e 's/[^0-9]//ig')

vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9]//ig')

[[ "$vrs1" == "$vrs2" ]] && {

  echo -e " \033[1;36m     TU SCRIPT YA ESTA ACTUALIZADO!\033[1;32m\n"

  rm /tmp/att >/dev/null 2>&1

  echo -e " \033[1;33m MAS INFO \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@t3mma\n"

  echo -ne " \033[1;31m ENTER \033[1;33mpara volver al \033[1;32mMENU! \033[0m"
  read

  menu

} || {

  echo -e "  \033[1;36mEXISTE UNA NUEVA ACTUALIZACIÓN DISPONIBLE!\033[1;33m\n"

  echo -e "  \033[1;33mMAS INFO \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@t3mma\n"

  echo -e "  \033[1;32mDETALLES DE ACTUALIZACIÓN:\033[0m\n"

  while read linha; do

    echo -e "  \033[1;37m- \033[1;33m$linha"

  done <"/tmp/att"

  echo " "

  echo -ne "  \033[1;32mDESEA ACTUALIZAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
  read res

  if [[ "$res" = s || "$res" = S ]]; then

    echo -e "\n\033[1;32m  INICIANDO ACTUALIZACIÓN..."

    sleep 3

    wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Plus >/dev/null 2>&1

    chmod +x Plus

    ./Plus

    clear

    echo -e "\033[1;32mSCRIPT ACTUALIZADO CON ÉXITO\033[0m\n"

    rm /tmp/att >/dev/null 2>&1

    echo -ne "\033[1;31mENTER \033[1;33mpara volver al \033[1;32mMENU!\033[0m"
    read

    menu

  else

    menu

  fi

}
