#!/bin/bash

if [ -d "/etc/squid/" ]; then
	payload="/etc/squid/payload.txt"
elif [ -d "/etc/squid3/" ]; then
	payload="/etc/squid3/payload.txt"
fi
tput setaf 7
tput setab 4
tput bold
printf '%35s%s%-10s\n' "Eliminar Host del Proxy Squid"
tput sgr0
if [ ! -f "$payload" ]; then
	tput setaf 7
	tput setab 4
	tput bold
	echo ""
	echo "Archivo $payload no encontrado"
	tput sgr0
	exit 1
else
	tput setaf 2
	tput bold
	echo ""
	echo "Dominios actuales en el archivo $payload:"
	tput sgr0
	tput setaf 3
	tput bold
	echo ""
	cat $payload
	echo ""
	tput sgr0
	read -p "Ingrese el dominio que desea eliminar de la lista: " host
	if [[ -z $host ]]; then
		tput setaf 7
		tput setab 4
		tput bold
		echo ""
		echo "¡Has ingresado un dominio vacío o inexistente!"
		echo ""
		tput sgr0
		exit 1
	else
		if [[ $(grep -c "^$host" $payload) -ne 1 ]]; then
			tput setaf 7
			tput setab 4
			tput bold
			echo ""
			echo "El dominio $host no se encontró en el archivo $payload"
			echo ""
			tput sgr0
			exit 1
		else
			grep -v "^$host" $payload >/tmp/a && mv /tmp/a $payload
			tput setaf 7
			tput setab 1
			tput bold
			echo ""
			echo "Archivo $payload actualizado, el dominio se ha eliminado con éxito:"
			tput sgr0
			tput setaf 3
			tput bold
			echo ""
			cat $payload
			echo ""
			tput sgr0
			if [ ! -f "/etc/init.d/squid3" ]; then
				service squid3 reload
			elif [ ! -f "/etc/init.d/squid" ]; then
				service squid reload
			fi
			tput setaf 7
			tput setab 1
			tput bold
			echo ""
			echo "¡El Proxy Squid se recargó con éxito!"
			echo ""
			tput sgr0
			exit 1
		fi
	fi
fi
