#!/bin/bash
FECHA=$(date +"%Y-%m-%d")
cor1='\033[1;31m'
cor2='\033[0;34m'
cor3='\033[1;35m'
clear
scor='\033[0m'
echo -e "\E[44;1;37m       MENU PSIPHON 🇦🇷⭐⭐⭐      \E[0m"
echo -e""
echo -e "\e[1;31m[\e[1;36m01\e[1;31m] \e[1;37m• \e[1;33mINICIAR o REINICIAR PSIPHON
\e[1;31m[\e[1;36m02\e[1;31m] \e[1;37m• \e[1;33mINSTALAR PSIPHON 443 \e[1;31m  \e[1;31m
[\e[1;36m03\e[1;31m] \e[1;37m• \e[1;33mVER PUERTOS \e[1;31m
[\e[1;36m04\e[1;31m] \e[1;37m• \e[1;33mVER CODIGO TARGET\e[1;31m
[\e[1;36m05\e[1;31m] \e[1;37m• \e[1;33mINSTALAR PSIPHON 80 \e[1;31m
[\e[1;36m06\e[1;31m] \e[1;37m• \e[1;33mVER CONECTADOS \e[1;31m
[\e[1;36m07\e[1;31m] \e[1;37m• \e[1;33mLIMPIAR RAM \e[1;31m
[\e[1;36m08\e[1;31m] \e[1;37m• \e[1;33mBORRAR PSIPHON ❌\e[1;31m
[\e[1;36m00\033[1;31m] \033[1;37m• \033[1;33mVOLVER \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m"
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\\033[0m"
echo ""
echo -ne "\033[1;32m   QUÉ DESEA HACER \033[1;33m??\033[0m: "
read n

case $n in
1 | 01)
   clear
   cd /root/psi && screen -dmS PSI ./psiphond run
   echo -ne "\n\033[1;31mListo \033[1;33mPsiphon Iniciado o  \033[1;32mReiniciado!\033[0m"
   read
   ;;
2 | 02)
   clear
   cd /root && mkdir psi && cd /root/psi && wget https://raw.githubusercontent.com/Psiphon-Labs/psiphon-tunnel-core-binaries/master/psiphond/psiphond && chmod 777 psiphond && ./psiphond --ipaddress 0.0.0.0 --protocol FRONTED-MEEK-OSSH:443 generate && screen -dmS PSI ./psiphond run && cat /root/psi/server-entry.dat
   echo ''
   echo -ne "\n\033[1;31mENTER \033[1;33mPARA VOLVER AL \033[1;32mMENU!\033[0m"
   read
   ;;
3 | 03)
   clear
   netstat -ntpl
   echo -ne "\n\033[1;31mENTER \033[1;33mPARA VOLVER AL \033[1;32mMENU!\033[0m"
   read
   ;;
   #menu
   #;;
4 | 04)
   clear
   cd /root/psi && cat /root/psi/server-entry.dat
   echo ''
   echo -ne "\n\033[1;31mENTER \033[1;33mPARA VOLVER AL \033[1;32mMENU!\033[0m"
   read
   ;;
5 | 05)
   cd /root && mkdir psi && cd /root/psi && wget https://raw.githubusercontent.com/Psiphon-Labs/psiphon-tunnel-core-binaries/master/psiphond/psiphond && chmod 777 psiphond && ./psiphond --ipaddress 0.0.0.0 --protocol FRONTED-MEEK-OSSH:80 generate && screen -dmS PSI ./psiphond run && cat /root/psi/server-entry.dat
   echo ''
   echo -ne "\n\033[1;31mENTER \033[1;33mPARA VOLVER AL \033[1;32mMENU!\033[0m"
   read
   ;;
6 | 06)
   clear
   verconectados
   echo -ne "\n\033[1;31mENTER \033[1;33mPARA VOLVER AL \033[1;32mMENU!\033[0m"
   read
   sleep 1
   ;;
7 | 07)
   echo ""
   echo -e "\033[1;31m   Limpiando RAM...\033[0m"
   sleep 1
   sync &
   sysctl -w vm.drop_caches=3 >/dev/null 2>&1
   menupsiphon
   ;;
8 | 08)
   rm -rf /root/psi
   menupsiphon
   ;;
0 | 00)
   menu
   ;;
*) echo "OPCIÓN INCORRECTA" ;;
esac
