#!/bin/bash

echo -e "\033[1;31mATENCION Amigo !!\033[0m"
echo " "
echo -e "\033[1;33mEsta Contraseña sera  para entrar en su servidor
\033[0m"
echo -e "\033[1;32mESCRIBE LA NUEVA CONTRASEÑA \033[1;32m
para continuar...\033[1;31m\033[0m"
read  -p : pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
echo -e "\033[1;31mCONTRASEÑA EDITADA CON EXITO!\033[0m"
sleep 5s
cd
clear

