#!/bin/bash
FECHA=$(date +"%Y-%m-%d")
cor1='\033[1;31m'
cor2='\033[0;34m'
cor3='\033[1;35m'
clear
scor='\033[0m'
echo -e "\E[44;1;37m    INSTALADOR UDP @T3MMA      \E[0m"
echo ""
echo -e "\e[1;31m[\e[1;36m01\e[1;31m] \e[1;37m• \e[1;33mUDP DEBIAN
\e[1;31m[\e[1;36m02\e[1;31m] \e[1;37m• \e[1;33mELIMINAR UDP
\e[1;31m[\e[1;36m03\e[1;31m] \e[1;37m• \e[1;33mVER CONECTADOS
\e[1;31m[\e[1;36m04\e[1;31m] \e[1;37m• \e[1;33mUDP UBUNTU 18
\e[1;31m[\e[1;36m05\e[1;31m] \e[1;37m• \e[1;33mUDP AUTO INSTALACION
\e[1;31m[\e[1;36m06\e[1;31m] \e[1;37m• \e[1;33mIR A Menu UDP
\e[1;31m[\e[1;36m07\e[1;31m] \e[1;37m• \e[1;33mUDP Redjoker256
\e[1;31m[\e[1;36m08\e[1;31m] \e[1;37m• \e[1;33mATRÁS
\e[1;31m[\e[1;36m00\e[1;31m] \e[1;37m• \e[1;33mVOVER AL MENÚ PRINCIPAL"
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\\033[0m"
echo ""
echo -ne "\033[1;32m   QUÉ DESEA HACER \033[1;33m??\033[0m: "
read n

case $n in
1 | 01)
   clear
   rm -rf /root/install.sh && wget https://raw.githubusercontent.com/vpsvip7/1s/main/install.sh && chmod 777 install.sh && ./install.sh
   echo -ne "\n\033[1;31mListo \033[1;33mComando menu  \033[1;32mPara terminar de instalar!\033[0m"
   read
   udp
   ;;
2 | 02)
   clear
   rm -rf /root/udp
   sleep 5
   ;;
3 | 03)
   clear
   verconectados
   sleep 6
   ;;
4 | 04)
   clear
   rm -rf /root/UDPserver.sh &&
      wget https://raw.githubusercontent.com/vpsvip7/2d/main/UDPserver.sh && chmod 777 UDPserver.sh && ./UDPserver.sh
   echo -ne "\n\033[1;31mEnter \033[1;33m Para volver al  \033[1;32mMenu!\033[0m"
   read
   udp
   ;;
5 | 05)
   clear
   wget https://raw.githubusercontent.com/vpsvip7/1s/main/udp-custom.sh -O install-udp && chmod +x install-udp && ./install-udp
   echo -ne "\n\033[1;31mEnter \033[1;33m Para volver al  \033[1;32mMenu!\033[0m"
   read
   ;;
6 | 06)
   udp
   ;;
7 | 07)
   git clone https://github.com/Redjoker256/Udpcustom.git && cd Udpcustom && chmod +x install.sh && ./install.sh
   menu
   ;;
8 | 08)
   udp-menu
   ;;
0 | 00)
   menu
   ;;
*) echo "Opción Incorrecta" ;;
esac
