#!/bin/bash
clear
fun_bar() {
   comando[0]="$1"
   comando[1]="$2"
   (
      [[ -e $HOME/fim ]] && rm $HOME/fim
      ${comando[0]} -y >/dev/null 2>&1
      ${comando[1]} -y >/dev/null 2>&1
      touch $HOME/fim
   ) >/dev/null 2>&1 &
   tput civis
   echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m["
   while true; do
      for ((i = 0; i < 18; i++)); do
         echo -ne "\033[1;31m#"
         sleep 0.1s
      done
      [[ -e $HOME/fim ]] && rm $HOME/fim && break
      echo -e "\033[1;33m]"
      sleep 1s
      tput cuu1
      tput dl1
      echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m["
   done
   echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
   tput cnorm
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7
tput setab 4
tput bold
printf '%40s%s%-12s\n' "INSTALANDO SLOWDNS DROP"
tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e ""
echo -e "      Este script realizará la instalación de"
echo -e "      slowdns para el tunnel DNS con Dropbear."
echo -e ""
echo -e "         \033[1;33mInstalador editado por @T3MMA \033[1;37m"
echo -e ""
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "ACTUALIZANDO LISTA DE PAQUETES..."
fun_att() {
   apt update && apt upgrade -y
}
fun_bar 'fun_att'
echo -e "INSTALANDO Y ACTUALIZANDO PAQUETES NECESARIOS..."
install_pkgs() {
   apt install screen -y
   apt install cron -y
   apt install iptables -y
   service cron reload
   service cron restart
   service iptables reload
   service iptables restart
}
fun_bar 'install_pkgs'
echo -e "BAJANDO BINARIO DNSTT..."
download_dnstt() {
   rm -rf /etc/slowdns
   mkdir /etc/slowdns
   cd /etc/slowdns/ && wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/dns-server
   chmod +x dns-server
}
fun_bar 'download_dnstt'
echo -e "CONFIGURANDO IPTABLES..."
ipt_set() {
   cd /etc
   rm -rf rc.local
   wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/rc.local
   chmod +x /etc/rc.local
   systemctl enable rc-local
   systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m ATENCIÓN EN ESTA ETAPA! \033[1;33m"
echo ""
echo -ne "\033[1;32m INFORME SU NS (NAMESERVER)\033[1;37m: "
read nameserver
cd /etc/slowdns
touch infons
echo $nameserver >infons
set_ns() {
   sleep 1
   wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/drop/startdns
   wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/drop/restartdns
   wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/slowdns-info
   chmod +x startdns
   chmod +x restartdns
   sed -i "s;1234;$nameserver;g" /etc/slowdns/startdns >/dev/null 2>&1
   sed -i "s;1234;$nameserver;g" /etc/slowdns/restartdns >/dev/null 2>&1
   cp startdns /bin/
   cp restartdns /bin/
}
fun_bar 'set_ns'
echo ""
echo "Verificando existencia de key"
sleep 2
echo ""
echo "      Por favor espere...   "
sleep 2
cd
key1="/root/server.key"
key2="/root/server.pub"
if [ -f $key1 ] && [ -f $key2 ]; then
   echo -e "Archivo de key encontrado!"
   sleep 1
   echo ""
   key() {
      echo "Como desea obtener su key?"
      echo ""
      echo -e "\033[0;31m[\e[0;33m 1 \e[0;31m]\033[m | Usar key existente en archivo"
      echo -e "\033[0;31m[\e[0;33m 2 \e[0;31m]\033[m | Eliminar archivo y generar nueva key"
      echo -e "\033[0;31m[\e[0;33m 3 \e[0;31m]\033[m | Eliminar archivo y usar key padrón"
      echo -e "\033[0;31m[\e[0;33m x \e[0;31m]\033[m | Abortar instalación"
      echo ""
      echo -ne "Digite una opción: " && read opcion
      case $opcion in
      1) Opcion1 ;;
      2) Opcion2 ;;
      3) Opcion3 ;;
      x) OpcionX ;;
      *)
         "Opcion incorrecta"
         echo
         key
         ;;
      esac
   }
   Opcion1() {
      echo -ne "Restaurando key existente..." && sleep 2 && echo "OK!"
      echo ""
      echo -e "FINALIZANDO..."
      finish_ist() {
         cd /etc/slowdns
         iptables -I INPUT -p udp --dport 5300 -j ACCEPT
         iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
         ./startdns
      }
      fun_bar 'finish_ist'
      clear
      echo -e "\033[1;31m INSTALACIÓN FINALIZADA!\033[0m"
      echo ""
      echo -ne "\033[1;33mSU NS:\033[0m " && cat /etc/slowdns/infons
      echo ""
      echo -ne "\033[1;33mSU KEY:\033[0m " && cat /root/server.pub
      echo ""
      echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
      echo ""
      echo -e "\033[1;33m SU KEY está guardado en el archivo /root/server.pub\033[0m"
      echo -e "\033[1;33mGuardelo en un lugar seguro, lo necesitará en el futuro!\033[0m"
      echo ""
      read -p "Presione [Enter] para volver al menu o CTRL+C para salir: "
      slowdns
   }
   Opcion2() {
      cd
      rm server.key server.pub
      echo "Generando nueva key"
      cd /etc/slowdns/
      ./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
      echo -e "FINALIZANDO..."
      finish_ist() {
         iptables -I INPUT -p udp --dport 5300 -j ACCEPT
         iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
         ./startdns
         cd
      }
      fun_bar 'finish_ist'
      clear
      echo -e "\033[1;31m INSTALACIÓN FINALIZADA!\033[0m"
      echo ""
      echo -ne "\033[1;33mSU NS:\033[0m " && cat /etc/slowdns/infons
      echo ""
      echo -ne "\033[1;33mSU KEY:\033[0m " && cat /root/server.pub
      echo ""
      echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
      echo ""
      echo -e "\033[1;33m SU KEY está guardado en el archivo /root/server.pub\033[0m"
      echo -e "\033[1;33mGuardelo en un lugar seguro, lo necesitará en el futuro!\033[0m"
      echo ""
      read -p "Presione [Enter] para volver al menu o CTRL+C para salir: "
      slowdns
   }
   Opcion3() {
      echo -e "Descargando el par de claves predeterminado..."
      cd
      rm server.key server.pub
      wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/server.key
      wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/server.pub
      sleep 1
      echo -e "Descarga Finalizada"
      sleep 1
      cd /etc/slowdns/
      echo -e "FINALIZANDO..."
      finish_ist() {
         iptables -I INPUT -p udp --dport 5300 -j ACCEPT
         iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
         ./startdns
         cd
      }
      fun_bar 'finish_ist'
      clear
      echo -e "\033[1;31m INSTALACIÓN FINALIZADA!\033[0m"
      echo ""
      echo -ne "\033[1;33mSU NS:\033[0m " && cat /etc/slowdns/infons
      echo ""
      echo -ne "\033[1;33mSU KEY:\033[0m " && cat /root/server.pub
      echo ""
      echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
      echo ""
      echo -e "\033[1;33m SU KEY está guardado en el archivo /root/server.pub\033[0m"
      echo -e "\033[1;33mGuardelo en un lugar seguro, lo necesitará en el futuro!\033[0m"
      echo ""
      read -p "Presione [Enter] para volver al menu o CTRL+C para salir: "
      slowdns
   }
   OpcionX() {
      exit
   }
   key
else
   echo -e "No existe una key en nuestros registros"
   echo ""
   key_gen() {
      echo "Como desea obtener su key?"
      echo ""
      echo -e "\033[0;31m[\e[0;33m 1 \e[0;31m]\033[m | Generar una instalación"
      echo -e "\033[0;31m[\e[0;33m 2 \e[0;31m]\033[m | Usar una key padrón"
      echo -e "\033[0;31m[\e[0;33m x \e[0;31m]\033[m | Abortar instalación"
      echo ""
      echo -ne "Digite una opción: " && read opc_key
      case $opc_key in
      1) opc_key1 ;;
      2) opc_key2 ;;
      x) opc_keyx ;;
      *)
         "Opcion incorrecta"
         echo
         key_gen
         ;;
      esac
   }
   opc_key1() {
      echo "Generando su key..."
      cd /etc/slowdns/
      ./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
      echo -e "FINALIZANDO..."
      finish_ist() {
         iptables -I INPUT -p udp --dport 5300 -j ACCEPT
         iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
         ./startdns
         cd
      }
      fun_bar 'finish_ist'
      clear
      echo -e "\033[1;31m INSTALACIÓN FINALIZADA!\033[0m"
      echo ""
      echo -ne "\033[1;33mSU NS:\033[0m " && cat /etc/slowdns/infons
      echo ""
      echo -ne "\033[1;33mSU KEY:\033[0m " && cat /root/server.pub
      echo ""
      echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
      echo ""
      echo -e "\033[1;33m SU KEY está guardado en el archivo /root/server.pub\033[0m"
      echo -e "\033[1;33mGuardelo en un lugar seguro, lo necesitará en el futuro!\033[0m"
      echo ""
      read -p "Presione [Enter] para volver al menu o CTRL+C para salir: "
      slowdns
   }
   opc_key2() {
      echo -e "Descargando el par de claves predeterminado..."
      cd
      wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/server.key
      wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/server.pub
      sleep 1
      echo -e "Descarga Finalizada"
      sleep 1
      cd /etc/slowdns/
      echo -e "FINALIZANDO..."
      finish_ist() {
         iptables -I INPUT -p udp --dport 5300 -j ACCEPT
         iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
         ./startdns
         cd
      }
      fun_bar 'finish_ist'
      clear
      echo -e "\033[1;31m INSTALACIÓN FINALIZADA!\033[0m"
      echo ""
      echo -ne "\033[1;33mSU NS:\033[0m " && cat /etc/slowdns/infons
      echo ""
      echo -ne "\033[1;33mSU KEY:\033[0m " && cat /root/server.pub
      echo ""
      echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
      echo ""
      echo -e "\033[1;33m SU KEY está guardado en el archivo /root/server.pub\033[0m"
      echo -e "\033[1;33mGuardelo en un lugar seguro, lo necesitará en el futuro!\033[0m"
      echo ""
      read -p "Presione [Enter] para volver al menu o CTRL+C para salir: "
      slowdns
   }
   opc_keyx() {
      echo "Abortando instalación"
      sleep 2
      slowdns
   }
   key_gen
fi
