#!/bin/bash
clear
slowdns() {
    echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
    tput setaf 7
    tput setab 4
    tput bold
    printf '%40s%s%-12s\n' "MENU SLOWDNS MANAGER V3.2"
    tput sgr0
    echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
    echo -e "\033[0;36m#===================================================#\033[m"
    echo -e "\033[0;36m# .|'''.|'||                '||''|. '|.   '|'.|'''.|#\033[m"
    echo -e "\033[0;36m# ||..  ' ||  ... ... ... ...||   || |'|   | ||..  '#\033[m"
    echo -e "\033[0;36m#  ''|||. ||.|  '|.||  ||  | ||    ||| '|. |  ''|||.#\033[m"
    echo -e "\033[0;36m#.     '||||||   || ||| |||  ||    |||   |||.     '|#\033[m"
    echo -e "\033[0;36m#|'....|'.||.'|..|'  |   |  .||...|'.|.   '||'....|'#\033[m"
    echo -e "\033[0;36m#---------------------------------------------------#\033[m"
    echo -e "\033[0;36m#       \033[m \033[0;31mSlowDNS | Disfruta cada momento!\033[m \033[0;36m          #\033[m"
    echo -e "\033[0;36m#===================================================#\033[m"
    echo ""
    echo -e "\033[0;31m[\e[0;33m01\e[0;31m]\033[m | Instalar SlowDNS SSH"
    echo -e "\033[0;31m[\e[0;33m02\e[0;31m]\033[m | Instalar SlowDNS SSL"
    echo -e "\033[0;31m[\e[0;33m03\e[0;31m]\033[m | Instalar SlowDNS DROP"
    echo -e "\033[0;31m[\e[0;33m04\e[0;31m]\033[m | Instalar SlowDNS SOCKS"
    echo -e "\033[0;31m[\e[0;33m05\e[0;31m]\033[m | Ver información"
    echo -e "\033[0;31m[\e[0;33m06\e[0;31m]\033[m | Iniciar SlowDNS"
    echo -e "\033[0;31m[\e[0;33m07\e[0;31m]\033[m | Reiniciar SlowDNS"
    echo -e "\033[0;31m[\e[0;33m08\e[0;31m]\033[m | Parar SlowDNS"
    echo -e "\033[0;31m[\e[0;33m09\e[0;31m]\033[m | Remover SlowDNS"
    echo -e "\033[0;31m[\e[0;33m10\e[0;31m]\033[m | Actualizar/Reinstalar"
    echo -e "\033[0;31m[\e[0;33m11\e[0;31m]\033[m | Remover Script"
    echo -e "\033[0;31m[\e[0;33m11\e[0;31m]\033[m | Volver al menú principal"
    echo -e "\033[0;31m[\e[0;33m00\e[0;31m]\033[m | SALIR"
    echo ""
    echo -ne "\033[0;36mQue desea hacer?:\0033[m " && read opcion
    case $opcion in
    1) Opcion1 ;;
    2) Opcion2 ;;
    3) Opcion3 ;;
    4) Opcion4 ;;
    5) Opcion5 ;;
    6) Opcion6 ;;
    7) Opcion7 ;;
    8) Opcion8 ;;
    9) Opcion9 ;;
    10) Opcion10 ;;
    11) Opcion11 ;;
    12) Opcion12 ;;
    0) Salir ;;
    *)
        "Opcion incorrecta"
        echo
        slowdns
        ;;
    esac
}

Opcion1() {
    clear
    bash /etc/slowdns/slowdns-ssh
}

Opcion2() {
    clear
    bash /etc/slowdns/slowdns-ssl
}

Opcion3() {
    clear
    bash /etc/slowdns/slowdns-drop
}

Opcion4() {
    clear
    bash /etc/slowdns/slowdns-socks
}

Opcion5() {
    clear
    bash /etc/slowdns/slowdns-info
}

Opcion6() {
    clear
    bash /etc/slowdns/startdns
}

Opcion7() {
    clear
    bash /etc/slowdns/restartdns
}

Opcion8() {
    clear
    bash /etc/slowdns/stopdns
}

Opcion9() {
    clear
    bash /etc/slowdns/stopdns
    bash /etc/slowdns/remove-slow
}

Opcion10() {
    clear
    wget https://raw.githubusercontent.com/T3mma/script-bot-sshplus/main/Slowdns/update
    chmod +x update
    bash update
}

Opcion11() {
    clear
    bash /etc/slowdns/remove-slow
    echo -e "\033[0;31mSlowDNS Manager Desinstalado!\033[0m"
    sleep 2
    rm /bin/slowdns
}
Opcion12() {
    menu
}

Salir() {
    clear
    exit
}
clear
slowdns
